"""
Professional Document Generator for Vasi AI
Generates beautifully formatted PDF and Word documents
"""

import os
from datetime import datetime
from io import BytesIO
import base64

# PDF Generation
try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
    PDF_AVAILABLE = True
    print("[OK] ReportLab loaded - PDF generation enabled")
except ImportError as e:
    PDF_AVAILABLE = False
    print(f"[WARNING] reportlab not available - PDF generation disabled: {e}")

# Word Generation
try:
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    DOCX_AVAILABLE = True
    print("[OK] python-docx loaded - Word generation enabled")
except ImportError as e:
    DOCX_AVAILABLE = False
    print(f"[WARNING] python-docx not available - Word generation disabled: {e}")


class DocumentGenerator:
    """Generate professional PDF and Word documents"""
    
    def __init__(self):
        self.output_dir = "generated_documents"
        os.makedirs(self.output_dir, exist_ok=True)
    
    def generate_pdf(self, title: str, content: str, author: str = "Vasi AI") -> tuple:
        """Generate a professional PDF document"""
        if not PDF_AVAILABLE:
            return None, "PDF generation not available. Install reportlab."
        
        try:
            # Create filename
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{title.replace(' ', '_')}_{timestamp}.pdf"
            filepath = os.path.join(self.output_dir, filename)
            
            # Create PDF
            doc = SimpleDocTemplate(filepath, pagesize=letter,
                                   rightMargin=72, leftMargin=72,
                                   topMargin=72, bottomMargin=18)
            
            # Container for the 'Flowable' objects
            elements = []
            
            # Define styles
            styles = getSampleStyleSheet()
            
            # Custom title style
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                textColor=colors.HexColor('#1e40af'),
                spaceAfter=30,
                alignment=TA_CENTER,
                fontName='Helvetica-Bold'
            )
            
            # Custom heading style
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=16,
                textColor=colors.HexColor('#2563eb'),
                spaceAfter=12,
                spaceBefore=12,
                fontName='Helvetica-Bold'
            )
            
            # Custom body style
            body_style = ParagraphStyle(
                'CustomBody',
                parent=styles['BodyText'],
                fontSize=11,
                alignment=TA_JUSTIFY,
                spaceAfter=12,
                leading=14,
                fontName='Helvetica'
            )
            
            # Add title
            elements.append(Paragraph(title, title_style))
            elements.append(Spacer(1, 0.2*inch))
            
            # Add metadata
            meta_text = f"<i>Generated by Vasi AI | {datetime.now().strftime('%B %d, %Y')}</i>"
            meta_style = ParagraphStyle('Meta', parent=styles['Normal'], fontSize=9, 
                                       textColor=colors.grey, alignment=TA_CENTER)
            elements.append(Paragraph(meta_text, meta_style))
            elements.append(Spacer(1, 0.3*inch))
            
            # Process content
            paragraphs = content.split('\n\n')
            for para in paragraphs:
                if para.strip():
                    # Check if it's a heading (starts with #)
                    if para.strip().startswith('#'):
                        heading_text = para.strip().lstrip('#').strip()
                        elements.append(Paragraph(heading_text, heading_style))
                    else:
                        # Regular paragraph
                        elements.append(Paragraph(para.strip(), body_style))
                        elements.append(Spacer(1, 0.1*inch))
            
            # Build PDF
            doc.build(elements)
            
            # Read file and convert to base64
            with open(filepath, 'rb') as f:
                pdf_data = f.read()
                pdf_b64 = base64.b64encode(pdf_data).decode('utf-8')
            
            return filepath, pdf_b64
            
        except Exception as e:
            print(f"[ERROR] PDF generation failed: {e}")
            return None, str(e)
    
    def generate_word(self, title: str, content: str, author: str = "Vasi AI") -> tuple:
        """Generate a professional Word document"""
        if not DOCX_AVAILABLE:
            return None, "Word generation not available. Install python-docx."
        
        try:
            # Create filename
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{title.replace(' ', '_')}_{timestamp}.docx"
            filepath = os.path.join(self.output_dir, filename)
            
            # Create document
            doc = Document()
            
            # Set document properties
            doc.core_properties.title = title
            doc.core_properties.author = author
            doc.core_properties.created = datetime.now()
            
            # Add title
            title_para = doc.add_heading(title, 0)
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            title_run = title_para.runs[0]
            title_run.font.color.rgb = RGBColor(30, 64, 175)  # Blue color
            title_run.font.size = Pt(24)
            
            # Add metadata
            meta_para = doc.add_paragraph()
            meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            meta_run = meta_para.add_run(f"Generated by Vasi AI | {datetime.now().strftime('%B %d, %Y')}")
            meta_run.font.size = Pt(9)
            meta_run.font.color.rgb = RGBColor(128, 128, 128)
            meta_run.italic = True
            
            doc.add_paragraph()  # Spacer
            
            # Process content
            paragraphs = content.split('\n\n')
            for para in paragraphs:
                if para.strip():
                    # Check if it's a heading
                    if para.strip().startswith('#'):
                        heading_text = para.strip().lstrip('#').strip()
                        heading = doc.add_heading(heading_text, level=1)
                        heading_run = heading.runs[0]
                        heading_run.font.color.rgb = RGBColor(37, 99, 235)
                    else:
                        # Regular paragraph
                        p = doc.add_paragraph(para.strip())
                        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
                        for run in p.runs:
                            run.font.name = 'Calibri'
                            run.font.size = Pt(11)
            
            # Save document
            doc.save(filepath)
            
            # Read file and convert to base64
            with open(filepath, 'rb') as f:
                docx_data = f.read()
                docx_b64 = base64.b64encode(docx_data).decode('utf-8')
            
            return filepath, docx_b64
            
        except Exception as e:
            print(f"[ERROR] Word generation failed: {e}")
            return None, str(e)


# Global instance
doc_generator = DocumentGenerator()
